import type { Metadata } from "next";
import { Inter, Fira_Code } from "next/font/google";
import "./globals.css";
import Header from "../components/header";
import Footer from "../components/footer";

const interSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

const firaCodeMono = Fira_Code({
  variable: "--font-firacode-mono",
  subsets: ["latin"],
});

//TODO what metadata do I use?
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  //TODo understand all html/css here
  return (
    <html lang="en">
      <body
        className={`${interSans.variable} ${firaCodeMono.variable} antialiased`}
      >
        <div className="max-w-7xl mx-auto min-h-screen flex flex-col">
          <Header />
          <main className="flex-1">
            <div className="relative isolate">
              <div
                aria-hidden="true"
                className="absolute blur-3xl inset-x-0 -top-40 -z-10 transform-gpu overflow-hidden sm:-top-80"
              >
                <div
                  style={{
                    clipPath:
                      "polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)",
                  }}
                  className="relative left-[calc(50%-11rem)] aspect-1155/678 w-144.5 -translate-x-1/2 rotate-30 bg-background-decorator opacity-30 sm:left-[calc(50%-30rem)] sm:w-288.75"
                />
              </div>
              {children}
              <div
                aria-hidden="true"
                className="blur-3xl absolute inset-x-0 top-[calc(100%-13rem)] -z-10 transform-gpu overflow-hidden  sm:top-[calc(100%-30rem)]"
              >
                <div
                  style={{
                    clipPath:
                      "polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)",
                  }}
                  className="relative left-[calc(50%+3rem)] aspect-1155/678 w-144.5 -translate-x-1/2 bg-background-decorator opacity-30 sm:left-[calc(50%+36rem)] sm:w-288.75"
                />
              </div>
            </div>
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
